services:
  postgres:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: jobber_auth # optional: initial database
    volumes:
      - postgres-data-myapp4:/var/lib/postgresql/data # bind mount to host folder
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      # Expose Redis to your host machine on the same port (6379)
      - '6379:6379'
    volumes:
      # Optional: persist Redis data
      - redis_data-myapp4:/data
    command: ['redis-server', '--save', '20', '1', '--loglevel', 'warning']

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'

  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

volumes:
  postgres-data-myapp4:
  redis_data-myapp4:
