import { USERS_PACKAGE_NAME } from './types/proto/users';

export const MICROSERVICES_CLIENTS = {
  ASYNC_SCORE_SERVICE_CLIENT: 'ASYNC_SCORE_SERVICE',
  SYNC_SCORE_SERVICE_CLIENT: 'SYNC_SCORE_SERVICE',
  GSYNC_SCORE_SERVICE_CLIENT: USERS_PACKAGE_NAME,
  NOTIFICATION_SERVICE_CLIENT: 'NOTIFICATION_SERVICE',
  KAFKA_SERCVICE_CLIENT: 'KAFKA_SERVICE',
  REDIS_SERVICE_CLIENT: 'REDIS_SERVICE',
};
